name: Release

on:
  push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“‚ checkout repository"
        uses: actions/checkout@v4
      
      - name: "ğŸš€ setup node"
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: "ğŸ› ï¸ install dependencies"
        run: npm ci

      - name: "ğŸ“¦ build package"
        run: npm run build --if-present

      - name: "ğŸ§ª run tests"
        run: npm test

      - name: "ğŸ“¤ release package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
